api/urls.py
from django.urls import path,include
from .views import SeatListView, SeatDetailView

urlpatterns = [
    path('', SeatListView.as_view()),
    path('<int:pk>', SeatDetailView.as_view())
]

bookings/urls.py
from django.urls import path,include
from . import views
    
app_name = 'bookings'

urlpatterns = [
    path('',views.bookings_events, name="bookings_events"),
    path('<slug>',views.bookings_dashboard, name="bookings_dashboard"),
    path('manage_bookings/<int:show_id>',views.manage_bookings_detail, name="manage_bookings_detail"),
    path('<slug>/manage_bookings',views.manage_bookings, name="manage_bookings"),
    path('statistics/<int:show_id>',views.statistics_detail, name="statistics_detail"),
    path('<slug>/statistics',views.statistics, name="statistics"),
    path('attendees/<int:show_id>',views.attendees_detail, name="attendees_detail"),
    path('<slug>/attendees',views.attendees, name="attendees"),
]

planetx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookings/models.py
from django.db import models
from django.conf import settings
from venue.models import Seats
from events.models import Events, Shows
from django.contrib.postgres.fields import ArrayField
from django.conf import settings
from django.db.models.signals import pre_save
from bookings.utils import unique_booking_id_generator

# Create your models here.
class Bookings(models.Model):
    booking_id = models.CharField(max_length=120, blank=True)
    c_name = models.CharField(max_length=200)
    c_email = models.CharField(max_length=50)
    c_phone = models.CharField(max_length=15)
    event = models.ForeignKey(Events, on_delete=models.CASCADE)
    show = models.ForeignKey(Shows, on_delete=models.CASCADE)
    booked_seats = models.CharField(max_length=100)
    booked_seats_name = models.CharField(max_length=200)
    booked_date = models.DateTimeField(auto_now_add=True)
    booked_price = models.IntegerField()
    booked_seats_count = models.IntegerField()

    class Meta:
        verbose_name_plural = "Bookings"

    def __str__(self):
        return str(self.booking_id) + "-" + str(self.c_name)


def pre_save_create_booking_id(sender, instance, *args, **kwargs):
    if not instance.booking_id:
        instance.booking_id = unique_booking_id_generator(instance)

pre_save.connect(pre_save_create_booking_id, sender=Bookings)

bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Sum, Count, Max
from events.models import Events, Shows, Category
from venue.models import Seats
from bookings.models import Bookings
from django.contrib.auth.decorators import login_required, user_passes_test
from django_filters.filters import Filter
from django_filters.fields import Lookup
from django.contrib import messages, auth
from django.template import RequestContext
from django.conf import settings

# Create your views here.
def bookings_events(request):
    events = Events.objects.filter(is_published=True).order_by('-created_date')
    inLive = Events.objects.filter(is_published=True).count()
    offline = Events.objects.filter(is_published=False).count()
    total = Events.objects.all().count()

    context = {'events': events, 'inLive': inLive,
               'offline': offline, 'total': total,}

    return render(request, 'bookings/bookings_events.html', context)

def bookings_dashboard(request, slug):
    event_detail = get_object_or_404(Events, slug=slug)
    shows = Shows.objects.order_by('date').filter(event=event_detail.id)

    total_revenue = Seats.objects.filter(event = event_detail.id).filter(is_booked = True).aggregate(Sum('price'))
    tickets_sold = Seats.objects.filter(event = event_detail.id).filter(is_booked = True).count()

    attendees = Bookings.objects.filter(event = event_detail.id).count()

    context = {
        'event_detail': event_detail,
        'shows': shows,
        'total_revenue':total_revenue,
        'tickets_sold':tickets_sold,
        'attendees':attendees,
    }

    return render(request, 'bookings/bookings_dashboard.html', context)

def manage_bookings(request, slug):
    event_detail = get_object_or_404(Events, slug=slug)
    shows = Shows.objects.order_by('date').filter(event=event_detail.id)
     
    context = {
        'event_detail': event_detail,
        'shows': shows,   
    }

    return render(request, 'bookings/manage_bookings.html', context)

def statistics(request, slug):
    event_detail = get_object_or_404(Events, slug=slug)
    shows = Shows.objects.order_by('date').filter(event=event_detail.id)
    total_revenue = Seats.objects.filter(event = event_detail.id).filter(is_booked = True).aggregate(Sum('price'))

    tickets_sold = Seats.objects.filter(event = event_detail.id).filter(is_booked = True).count()
    seats_avail = Seats.objects.filter(event = event_detail.id).count()
 
    #queries for chart
    daily_count = Bookings.objects.filter(event = event_detail.id).values('booked_date__date').order_by('booked_date__date').annotate(sum =Sum('booked_seats_count'))
    daily_price = Bookings.objects.filter(event = event_detail.id ).values('booked_date__date').order_by('booked_date__date').annotate(sum =Sum('booked_price'))
    
    show_id = Shows.objects.values('id').filter(event = event_detail.id)
    total_seats = Seats.objects.filter(show__in = show_id)
 
    #for category_chart
    category_count = Seats.objects.filter(event = event_detail.id).filter(is_booked = True).values('category__category').annotate(count = Count('category_id'))
   
    print(category_count)

    context = {
        'total_revenue':total_revenue,
        'tickets_sold':tickets_sold,
        'seats_avail':seats_avail,
        'event_detail': event_detail,
        'shows': shows,
        'daily_count':daily_count,
        'daily_price':daily_price,
        'total_seats':total_seats,
        'category_count':category_count,
    }
    
    return render(request, 'bookings/statistics.html', context)


def statistics_detail(request, show_id):
    show = get_object_or_404(Shows, pk=show_id)
    dates = Shows.objects.order_by('date').filter(name=show.name).filter(is_full=False)

    tickets_sold = Seats.objects.filter(show = show.id).filter(is_booked = True).count()
    total_seats = Seats.objects.filter(show = show.id).count()

    daily_count = Bookings.objects.filter(show = show.id).values('booked_date__date').order_by('booked_date__date').annotate(sum = Sum('booked_seats_count'))
    category_count = Seats.objects.filter(show = show.id).filter(is_booked = True).values('category__category').annotate(count = Count('category_id'))
     
    context = {
        'show': show,
        'dates':dates,
        'tickets_sold':tickets_sold,
        'total_seats':total_seats,
        'daily_count':daily_count,
        'category_count':category_count,
    }

    return render(request, 'bookings/statistics_detail.html', context)

def manage_bookings_detail(request, show_id):
    show = get_object_or_404(Shows, pk=show_id)
    dates = Shows.objects.order_by('date').filter(name=show.name).filter(is_full=False)
    bookings = Bookings.objects.filter(show = show_id).order_by('-booked_date')
    bookings_done = Bookings.objects.filter(show = show_id).count()
    seats_avail = Seats.objects.filter(show=show_id).count()

    # print(bookings_done, seats_avail)
    # b_seats = bookings.values_list("booked_seats", flat=True) 
    # b_seats_list = list(b_seats)

    context = {'show': show, 'dates': dates, 'bookings':bookings, 'bookings_done':bookings_done, 'seats_avail':seats_avail,}
    return render(request, 'bookings/manage_bookings_detail.html', context)

def attendees(request, slug):
    event_detail = get_object_or_404(Events, slug=slug)
    shows = Shows.objects.order_by('date').filter(event=event_detail.id)
    attendees = Bookings.objects.filter(event = event_detail.id).order_by('-booked_date')

    context = {
        'event_detail': event_detail,
        'shows': shows,
        'attendees':attendees,
    }
        
    return render(request, 'bookings/attendees.html', context)

def attendees_detail(request, show_id):
    show = get_object_or_404(Shows, pk=show_id)
    dates = Shows.objects.order_by('date').filter(name=show.name).filter(is_full=False)
    attendees = Bookings.objects.filter(show = show_id).order_by('-booked_date')

    context = {
        'show': show,
        'dates':dates,
        'attendees':attendees,
    }

    return render(request, 'bookings/attendees_detail.html', context)

pages/templates/bookings/attendees.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% include 'partials/_navbar.html' %}
{% include 'partials/_datatables.html' %}
<section class="attendees">
    <header class="eventsHeader">
        <div class="container">
            <h4>{{ event_detail.name }} - Event Attendees</h4>
        </div>
    </header>
    <div class="container mt-2">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'bookings:bookings_events' %}">Event Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{% url 'bookings:bookings_dashboard' slug=event_detail.slug %}">{{ event_detail.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Event Attendees</li>
            </ol>
        </nav>
        <div class="attendeesFilter col-md-6">
            <div class="form-group">
                <label>Attendees for :</label>
                <div class="dropdown show">
                    <a class="btn btn-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Please select a show
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        {% for shows in shows %}
                            <a class="dropdown-item" href="{% url 'bookings:attendees_detail' shows.id %}">{{ shows.date }}, {{ shows.time }}</a>
                        {% endfor %} 
                    </div>
                </div>
            </div>
        </div>
        <hr>
        {% if attendees %}
        <div class="heading text-center">
            <h5>{{ event_detail.name }} - Attendees for all shows</h5>
        </div>
        <div class="attendeesTable mt-5">
            <table id="attendeesTable" class="table table-primary text-center mt-5">
                <thead>
                    <tr>
                        <th scope="col">Booking Id</th>
                        <th scope="col">Customer Name</th>
                        <th scope="col">show Date & time</th>
                        <th scope="col">Booked Date</th>
                        <th scope="col">Booked Seats</th>
                        <th scope="col">Phone Number</th>
                        <th scope="col">Amount Paid</th>
                    </tr>
                </thead>
                <tbody>
                    {% for attendees in attendees %}
                        <tr>
                            <td>{{ attendees.booking_id }}</td>
                            <td>{{ attendees.c_name }}</td>
                            <td>{{ attendees.show.date }}, {{ attendees.show.time }}</td>
                            <td>{{ attendees.booked_date | date}}</td>
                            <td>{{ attendees.booked_seats_name }}</td>
                            <td>{{ attendees.c_phone }}</td>
                            <td>
                                {{ attendees.booked_price }}
                                <small class="text-muted">KWD</small>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
            <div class="notAvailable">
                <p>Please select a show to see attendees</p>
            </div>
        {% endif %}
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock %}

pages/templates/bookings/attendees_detail.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% include 'partials/_navbar.html' %}
{% include 'partials/_datatables.html' %}
<section class="attendees">
    <header class="eventsHeader">
        <div class="container">
            <h4>{{ show.event.name }} - Event Attendees</h4>
        </div>
    </header>
    <div class="container mt-2">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'bookings:bookings_events' %}">Event Dashboard</a></li>
                <li class="breadcrumb-item"><a
                        href="{% url 'bookings:bookings_dashboard' slug=show.event.slug %}">{{ show.event.name }}</a>
                </li>
                <li class="breadcrumb-item"><a href="{% url 'bookings:attendees' slug=show.event.slug %}">Event
                        Attendees</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ show.date }}, {{ show.time }}</li>
            </ol>
        </nav>
        <div class="attendeesFilter col-md-6">
            <div class="form-group">
                <label>Attendees For:</label>
                <div class="dropdown show">
                    <a class="btn btn-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ show.date }}, {{ show.time }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'bookings:attendees' slug=show.event.slug %}">All
                            Shows</a>
                        {% for dates in dates %}
                            {% if dates.date != show.date %}
                                <a class="dropdown-item" href="{% url 'bookings:attendees_detail' dates.id %}">{{ dates.date }},
                                    {{ dates.time }}
                                </a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div> 
        </div>
        <hr>
        <div class="heading text-center">
            <h5>{{ show.event.name }} - {{ show.date}},{{ show.time }}</h5>
        </div>
        <div class="attendeesTable">
            <table id="attendeesTable" class="table table-primary text-center mt-5">
                <thead>
                    <tr>
                        <th scope="col">Booking Id</th>
                        <th scope="col">Customer Name</th>
                        <th scope="col">Booked Date</th>
                        <th scope="col">Booked Seats</th>
                        <th scope="col">Phone Number</th>
                        <th scope="col">Amount Paid</th>
                    </tr>
                </thead>
                <tbody>
                    {% for attendees in attendees %}
                        <tr>
                            <td>{{ attendees.booking_id }}</td>
                            <td>{{ attendees.c_name }}</td>
                            <td>{{ attendees.booked_date | date }}</td>
                            <td>{{ attendees.booked_seats_name }}</td>
                            <td>{{ attendees.c_phone }}</td>
                            <td>
                                {{ attendees.booked_price }}
                                <small class="text-muted">KWD</small>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock %}

pages/templates/bookings/bookings_dashboard.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% include 'partials/_navbar.html' %}
<section class="bookingsDashboard">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'bookings:bookings_events' %}">Event Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ event_detail.name }}</li>
            </ol>
        </nav>
        <div class="heading">
            <h4>{{ event_detail.name }}</h4>
        </div>
        <div class="stats_heading mt-4">
            <div class="row">
                <div class="col-md-3">
                    <div class="bookingStatsCard">
                        <p><small class="text-muted">KWD</small> <span class="primary-color">{{ total_revenue.price__sum }}</span></p>
                        <small class="text-muted">Net Sales</small>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="bookingStatsCard">
                        <p>{{ tickets_sold }}</p>
                        <small class="text-muted">Tickets Sold</small>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="bookingStatsCard">
                        <p>{{ attendees }}</p>
                        <small class="text-muted">Total Attendees</small>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row mt-4">
            <div class="col-md-2">
                <a href="{% url 'bookings:manage_bookings' slug=event_detail.slug %}">
                    <div class="optionCard">
                        <div class="optionCard__icon">
                            <i class="far fa-bookmark"></i>
                        </div>
                        <div class="optionCard__details">
                            <h6>Manage Bookings</h6>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-2">
                <a href="{% url 'bookings:statistics' slug=event_detail.slug %}">
                    <div class="optionCard">
                        <div class="optionCard__icon">
                            <i class="fas fa-signal"></i>
                        </div>
                        <div class="optionCard__details">
                            <h6>Event Statistics</h6>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-2">
                <a href="{% url 'bookings:attendees' slug=event_detail.slug %}">
                    <div class="optionCard">
                        <div class="optionCard__icon">
                            <i class="fas fa-user-friends"></i>
                        </div>
                        <div class="optionCard__details">
                            <h6>Event Attendees</h6>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-2">
                <a href="#">
                    <div class="optionCard">
                        <div class="optionCard__icon">
                            <i class="fas fa-file-alt"></i>
                        </div>
                        <div class="optionCard__details">
                            <h6>Event Reports</h6>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-2">
                <a href="#">
                    <div class="optionCard">
                        <div class="optionCard__icon">
                            <i class="fas fa-money-check-alt"></i>
                        </div>
                        <div class="optionCard__details">
                            <h6>Payment Details</h6>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-2">
                <a href="#">
                    <div class="optionCard">
                        <div class="optionCard__icon">
                            <i class="fas fa-ticket-alt"></i>
                        </div>
                        <div class="optionCard__details">
                            <h6>Offline Tickets</h6>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock %}

pages/templates/bookings/manage_bookings_detail.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% include 'partials/_navbar.html' %}
<section class="manageBookingsDetail">
    <header class="eventsHeader">
        <div class="container p-5 text-center">
            <h3>{{ show.event.name }}</h3>
        </div>
    </header>
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'bookings:bookings_events' %}">Event Dashboard</a></li>
                <li class="breadcrumb-item"><a
                        href="{% url 'bookings:bookings_dashboard' slug=show.event.slug %}">{{ show.event.name }}</a>
                </li>
                <li class="breadcrumb-item"><a href="{% url 'bookings:manage_bookings' slug=show.event.slug %}">Manage
                        Bookings</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ show.date | date:"d M Y" }},
                    {{ show.time | time:"H:i"}}</li>
            </ol>
        </nav>
        <div class="showDates">
            {% for dates in dates %}
            {% if dates.date != show.date %}
            <a class="badge badge-primary"
                href="{% url 'bookings:manage_bookings_detail' dates.id %}">{{ dates.date }},
                {{ dates.time }}</a>
            {% endif %}
            {% endfor %}
        </div>
        <hr>
        {% if bookings %}
        <div class="bookings mt-4">
            <div class="row">
                {% for bookings in bookings %}
                    <div class="bookingsCard mr-1 mb-1">
                        <div class="bookingsCard__id">
                            <p>{{ bookings.booking_id }}</p>
                        </div>
                        <div class="bookingsCard__details">
                            <p>{{bookings.c_name}}</p>
                            <p>{{bookings.c_email}}</p>
                            <p>{{bookings.c_phone}}</p>
                            <p>Seats Booked :</p>
                            <p>{{ bookings.booked_seats_name }}</p>
                            <small class="text-muted">{{ bookings.booked_date }}</small>
                        </div>
                    </div> 
                {% endfor %}
            </div>
            {% else %}
                <div class="notAvailable">
                    <p>No Bookings Done Yet.</p>
                </div>
            {% endif %}
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock %}

pages/templates/bookings/statistics_detail.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% include 'partials/_navbar.html' %}
{% include 'partials/_datatables.html' %}
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<section class="bookings_stats">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <li class="breadcrumb-item"><a href="{% url 'bookings:bookings_events' %}">Event Dashboard</a></li>
                <li class="breadcrumb-item"><a
                        href="{% url 'bookings:bookings_dashboard' slug=show.event.slug %}">{{ show.event.name }}</a>
                </li>
                <li class="breadcrumb-item"><a href="{% url 'bookings:statistics' slug=show.event.slug %}">Event
                        Statistics</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">{{ show.date | date:"d M Y" }},
                    {{ show.time | time:"H:i"}}</li>
            </ol>
        </nav>
        <div class="statisticsFilter col-md-6">
            <div class="form-group">               
                <label>Stats For :</label>
                <div class="dropdown show">
                    <a class="btn btn-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Please select a show
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'bookings:statistics' slug=show.event.slug %}">All
                            Shows</a>
                        {% for dates in dates %}
                            {% if dates.date != show.date %}
                            <a class="dropdown-item"
                                href="{% url 'bookings:statistics_detail' dates.id %}">{{ dates.date }},
                                {{ dates.time }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="heading">
            <h5>{{ show.event.name }} - {{ show.date }}, {{ show.time }}</h5>
        </div>
        <div class="ticketSales__progress mt-2">
            <small>{{tickets_sold}} tickets sold out of {{total_seats}}</small>
            <div class="progress">
                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                    aria-valuenow="{{ tickets_sold }}" aria-valuemin="0" aria-valuemax="100"
                    style="width:{{tickets_sold | mul:5}}%"></div>
            </div>
        </div>
        <div class="tickets_sold_chart mt-5">
            <div class="border" id="tickets_sold" style="min-width: 310px; height: 450px; margin: 0 auto"></div>
            <script>
                _categories = [{% for date in daily_count %} "{{ date.booked_date__date|date:"SHORT_DATE_FORMAT" }}", {% endfor %}]
                _values = [{% for date in daily_count %}{{ date.sum }},{% endfor %}]

                Highcharts.chart('tickets_sold', {
                    chart: {
                        type: 'line'
                    },
                    title: {
                        text: 'Daily Ticket Sales'
                    },
                    xAxis: {
                        categories: _categories,
                        crosshair: true
                    },
                    yAxis: {
                        min: 0,
                        title: {
                            text: 'Tickets Sold'
                        }
                    },
                    tooltip: {
                        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                        pointFormat: '<tr><td style="padding:0"><b>Tickets Sold: {point.y}</b></td></tr>',
                        footerFormat: '</table>',
                        shared: true,
                        useHTML: true
                    },
                    plotOptions: {
                        column: {
                            pointPadding: 0.2,
                            borderWidth: 0
                        }
                    },
                    series: [{
                        name: 'Tickets',
                        data: _values
                    }]
                });
            </script>
        </div>
        <hr>
        <div class="category_chart mt-5">
            <div class="category border" id="category_chart" style="min-width: 310px; height: 450px; margin: 0 auto">
            </div>
            <script>
                Highcharts.chart('category_chart', {
                    chart: {
                        plotBackgroundColor: null,
                        plotBorderWidth: null,
                        plotShadow: false,
                        type: 'pie'
                    },
                    title: {
                        text: 'Tickets Sales By Category'
                    },
                    tooltip: {
                        pointFormat: '{series.name}: <b>{point.y}</b>'
                    },
                    accessibility: {
                        point: {
                            valueSuffix: '%'
                        }
                    },
                    plotOptions: {
                        pie: {
                            allowPointSelect: true,
                            cursor: 'pointer',
                            dataLabels: {
                                enabled: false
                            },
                            showInLegend: true
                        }
                    },
                    series: [{
                        name: 'Tickets',
                        colorByPoint: true,
                        data: [
                            {% for category in category_count %}
                        {
                        name: '{{ category.category__category }}',
                        y: {{ category.count }}
                                    },
                    {% endfor %}
                    ]
                    }]
                });
            </script>
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock %}