api/urls.py
from django.urls import path,include
from .views import SeatListView, SeatDetailView

urlpatterns = [
    path('', SeatListView.as_view()),
    path('<int:pk>', SeatDetailView.as_view())
]

events/urls.py
from django.urls import path,include
from . import views
    
app_name = 'events'

urlpatterns = [
    path('',views.events, name="events"),
    path('<int:show_id>/checkout',views.checkout, name="checkout"),
    path('<int:show_id>/booking_confirmation',views.booking_confirmation, name="booking_confirmation"),
    path('<int:show_id>',views.show, name="show"),
    path('<slug>',views.event, name="event"),
]

planetx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from django.conf import settings

class Events(models.Model):
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, blank=True)
    desc = models.TextField()
    location = models.CharField(max_length=200)
    release_date = models.DateField()
    starting_price = models.IntegerField()
    cast = models.TextField(blank=True)
    cover_image = models.ImageField(blank=True)
    promo = EmbedVideoField(blank=True)
    is_published = models.BooleanField(default=False)
    is_cover = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)

    def snippet(self):
        return self.desc[:120] + ''

    def event_snippet(self):
        return self.desc[:500] + ' ...'

    class Meta:
        verbose_name_plural = "Events"

    def __str__(self):
        return self.name


class Shows(models.Model):
    name = models.CharField(max_length=200)
    event = models.ForeignKey(Events, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    is_published = models.BooleanField(default=False)
    is_full = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Shows"

    def __str__(self):
        return str(self.event) + "-" + str(self.name) + "-" + str(self.date) + "-" + str(self.time)


class Category(models.Model):
    category = models.CharField(max_length=100)
    event = models.ForeignKey(Events, on_delete=models.CASCADE)
    show = models.ForeignKey(Shows, on_delete=models.CASCADE)
    color = models.CharField(max_length=10)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return str(self.category)

events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Sum, Count, Max
from events.models import Events, Shows
from venue.models import Seats
from bookings.models import Bookings
from django.contrib.auth.decorators import login_required, user_passes_test
from django_filters.filters import Filter
from django_filters.fields import Lookup
from django.contrib import messages, auth
from django.template import RequestContext
from django.conf import settings

def events(request):
    events  = Events.objects.order_by('-created_date')
    context = { 'events':events }
    
    return render(request, 'events/events.html', context)

def event(request, slug):
    event_detail = get_object_or_404(Events, slug=slug)
    shows = Shows.objects.order_by('date').filter(event=event_detail.id)
    # shows = Shows.objects.order_by('date').filter(is_published=True)

    context = {
        'event_detail': event_detail,
        'shows': shows
    } 

    return render(request, 'events/event.html', context)

def show(request, show_id):
    show = get_object_or_404(Shows, pk=show_id)
    dates = Shows.objects.order_by('date').filter(name=show.name).filter(is_full=False)
    context = {'show':show, 'dates':dates, }
    if request.method == 'POST':
        #Get form values
        ticketTotal = request.POST['ticketTotal']
        seatId = request.POST['seatId']
        seatName = request.POST['seatName']
        request.session['seatId'] = request.POST

        if seatId == '':
            messages.error(request, 'Please select seats to continue !')
            return render(request, 'events/show.html', context)
        else:
            if seatName == '':
                messages.error(request, 'Please select seats to continue !')
                return render(request, 'events/show.html', context)
            else:
                if ticketTotal == '':
                    messages.error(request, 'Please select seats to continue !')
                    return render(request, 'events/show.html', context)
            return redirect('/events/'+ str(show_id) +'/checkout')
    return render(request, 'events/show.html', context)

def checkout(request, show_id,):
    show = get_object_or_404(Shows, pk=show_id)
    bookings = Bookings.objects.all()
    seatId = request.session.get('seatId')
    sId = (seatId['seatId'])
    seatName = (seatId['seatName'])
    #converting strings into array
    sIdx = sId.split(',')
    # removing last empty item in the array
    sIdx = sIdx[:-1]
    
    #converting array into string
    # sIdx = ''.join(sId)

    f_seats = Seats.objects.filter(id__in=sIdx)
    price = Seats.objects.filter(id__in=sIdx).aggregate(Sum('price'))['price__sum']
    tickets = len(sIdx)
    eventId = Shows.objects.values('event_id').filter(id = show_id)
    showId = Shows.objects.values('id').filter(id = show_id)

    context = {
       'f_seats':f_seats,
       'price': price,
       'show': show,
    }

    if request.method == 'POST': 
        seats = Seats.objects.filter(id__in = sIdx)
        seats.update(is_booked=True)

        c_name = request.POST['name']
        c_email = request.POST['email']
        c_phone = request.POST['phoneNumber']
        eventId = eventId
        showId = showId
        seatsId = sId
        seatsName = seatName
        seatsPrice = price

        if bookings.filter( booked_seats = seatsId).exists():
            messages.error(request, 'Selected seat already booked, Please try again !')
            return redirect('home')
        else:
            #submitting form to the database
            bookings = Bookings(
            c_name = c_name,
            c_email = c_email,
            c_phone = c_phone,
            event_id = eventId,
            show_id = showId,
            booked_seats = seatsId,
            booked_seats_name = seatsName,
            booked_price = seatsPrice,
            booked_seats_count= tickets
            )

            b_seats = Bookings.objects.filter(booked_seats = sId)
            print(b_seats)

            context = { 'f_seats':f_seats, 'price':price, 'tickets':tickets, 'b_seats':b_seats,
            'show': show, 'c_name':c_name, 'c_email':c_email, 'c_phone':c_phone, 'booked_seats':seatsId,}

            bookings.save()
            return render(request, 'events/booking_confirmation.html', context)
    return render(request, 'events/checkout.html', context)

def booking_confirmation(request, show_id,):
    show = get_object_or_404(Shows, pk=show_id)
    
    return render(request, 'events/booking_confirmation.html')

pages/templates/events/booking_confirmation.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% include 'partials/_navbar.html' %}
<section class="bookingConfirmation">
    <div class="col-lg-4 col-md-8 col-sm-8 offset-lg-4 ticketBox">
        <div class="ticketBox__header">
            <div class="thumbs">
                <i class="far fa-thumbs-up"></i>
            </div>
            <p>Thanks for booking with us !</p>
            <p>Booking ID : <span class="bookingId">
                {% for b_seats in b_seats %}
                    {{ b_seats.booking_id }}
                {% endfor %}
            </span></p>
        </div>
        <div class="ticketBox__body">
            <div class="ticketBox__customer">
                <p class="ticketBox__cname">{{ c_name }}</p>
                <p class="text-muted">{{ c_phone }}</p>
            </div>
            <hr>
            <div class="row mt-4 justify-content-center">
                <div class="col-md-5">
                    <p class="ticketBox__title">{{ show.event }}</p>
                    <p>{{ show.date | date:"d M Y" }} , {{ show.time | time:"H:i"}}</p>
                </div>
                <div class="col-md-3">
                    <img src={{show.event.cover_image.url}} class="img-fluid" alt={{show.event}}>
                </div>
            </div>
            <div class="row mt-4 text-center">
                <div class="col-md-4">
                    <p class="text-primary">Tickets</p>
                    <p>{{ tickets }}</p>
                </div>
                <div class="col-md-4">
                    <p class="text-primary">Seats</p>
                    <p>
                        {% for f_seats in f_seats %}
                            {{ f_seats.rt }}{{ f_seats.sname }},
                        {% endfor%}
                    </p>
                </div>
                <div class="col-md-4">
                    <p class="text-primary">Price</p>
                    <p>{{ price }} KWD</p>
                </div>
            </div>
            <hr>
            <p class="ticketBox__location text-muted text-center"><i class="fas fa-map-marker-alt mr-2"></i> {{ show.event.location }}</p>
            <div class="form-group text-center mt-4">
                <button class="btn btn-primary btn-sm">Download Ticket</button>
            </div>
            <div class="form-group text-center mt-4">
                <a href="/" class="btn-link">Back To Home</a>
            </div>
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock %}

pages/templates/events/checkout.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% include 'partials/_navbar.html' %}
<section class="checkout">
    <header class="header">
        <div class="container">
            <div class="heading">
                <h4>Checkout Page</h4>
            </div>
        </div>
    </header>
    <div class="container checkoutMain">
        <div class="row">
            <div class="col-md-7">
                <div class="contactDetails">
                    <div class="contactForm">
                        <h6>Your Contact Details</h6>
                        <small class="text-muted">We will only ever contact you about your booking</small>
                        <hr>
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="exampleInputEmail1">Your Name</label>
                                <input type="text" class="form-control" name="name"
                                    placeholder="Please enter you full name" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Email</label>
                                <input type="email" class="form-control" name="email"
                                    placeholder="Please enter your valid email" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Phone Number</label>
                                <input type="text" class="form-control" name="phoneNumber"
                                    placeholder="Please enter your phone number" required>
                            </div>
                            <div class="form-group form-check">
                                <input type="checkbox" class="form-check-input" id="terms" required>
                                <label class="form-check-label" for="exampleCheck1">I agree to terms &
                                    conditions</label>
                                <small id="emailHelp" class="form-text text-muted">Please confirm you agree to terms and
                                    conditions of sales and aware that most theatres do not accept exchanges or
                                    refunds.</small>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Confirm purchase</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="orderDetails">
                    <div class="timer text-center">
                        <h6><i class="fas fa-info-circle text-primary" data-toggle="tooltip" data-placement="top"
                                title="Due to high demand, your chosen tickets can only be held for a limited time and then removed automatically."></i>
                            <span id="countdown">10:00</span></h6>
                        <p class="text-muted">Remaining to complete order</p>
                        <hr>
                        <a class="btn btn-danger btn-sm" onclick="cancelTicket()"><i class="fas fa-times-circle"></i>
                            Cancel Ticket</a>
                    </div>
                    <div class="orderCheckout">
                        <h6>Order Summary</h6>
                        <small class="text-muted">Please check the details of your order before proceeding</small>
                        <div class="row">
                            <div class="col-md-4">
                                <img src={{show.event.cover_image.url}} class="img-fluid" alt={{ show.event }}>
                            </div>
                            <div class="col-md-8">
                                <h6>{{ show.event }}</h6>
                                <p>{{ show.date | date:"d M Y" }}, {{ show.time | time:"H:i" }}</p>
                                <p>{{ show.event.location }}</p>
                            </div>
                        </div>
                        <hr>
                        <table class="table borderless">
                            <thead>
                                <tr>
                                    <th>Seat Name</th>
                                    <th>Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for f_seats in f_seats %}
                                <tr>
                                    <td>{{ f_seats.rt }}{{ f_seats.sname }}</td>
                                    <td>{{ f_seats.price }} KWD</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <th>Order Total</th>
                                <th>{{ price }} KWD</th>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/timer.js' %}"></script>
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
    function cancelTicket() {
        if (confirm('Are you sure you want to cancel this ticket ?')) {
            window.location.href = "/emptybasket";
        }
    }
</script>
{% include 'partials/_footer.html' %}
{% endblock %}

pages/templates/events/event.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% include 'partials/_navbar.html' %}
<section class="event">
    <header class="eventsHeader">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <img src="{{event_detail.cover_image.url}}" class="img-fluid" alt={{event_detail.name}} />
                </div>
                <div class="col-md-7">
                    <h3>{{ event_detail.name }}</h3>
                    <p>{{ event_detail.event_snippet }}</p>
                    <p>{{ event_detail.location }}</p>  
                    <p>Tickets starting from {{ event_detail.starting_price }} KWD</p>
                </div>
            </div>
        </div>
    </header>
    <div class="shows">
        <div class="container">   
            <ul class="list-group mt-5">
                <li class="list-group-item active">Available Shows</li>
                {% for shows in shows %}
                    <li class="list-group-item">
                       <div class="row p-1 justify-content-between">
                           <div class="date">
                               {{ shows.date | date:"d M Y" }} , {{shows.time }}
                           </div>
                           <div class="venue">
                                {{ event_detail.location }}
                           </div>
                           <div class="showLink">
                                <a href="{% url 'events:show' shows.id %}" class="btn btn-primary btn-sm
                                {% if shows.is_full %}
                                    disabled
                                {% endif %}">
                                {% if shows.is_full %}Sold out{% else %}See Tickets{% endif %}</a>
                            </div>
                       </div> 
                    </li>
                {% endfor %}
              </ul>
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock %}

pages/templates/events/events.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% include 'partials/_navbar.html' %}
<section class="events">
    <div class="container">
        <h3>Events</h3>
        <div class="row">
            {% for events in events %}
            <div class="col-md-6">
                <a href="{% url 'events:event' slug=events.slug %}">
                    <div class="jumboCard">
                        <img src="{{ events.cover_image.url }}" class="img-fluid" alt={{events.name}} />
                        <div class="jumboCard__details">
                            <h4>{{ events.name }}</h4>
                            <p>{{ events.snippet }}</p>
                            <a href="{% url 'events:event' slug=events.slug %}" class="btn btn-primary">Get Tickets</a>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% include 'partials/_footer.html' %}
{% endblock %}

pages/templates/events/show.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% include 'partials/_alerts.html' %}
{% include 'partials/_navbar.html' %}
<section class="show">
    <form>
        <input name="apiLink" type="hidden" id="apiLink" value="http://127.0.0.1:8000/api/?show={{show.id}}" />
    </form>
    <header class="showHeader">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2 col-md-2 col-lg-2">
                    <img src={{show.event.cover_image.url}} class="showImg" alt={{show.event}}>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-4 showDetails">
                    <h6>{{ show.event }}</h6>
                    <p>{{ show.date | date:"d M Y" }} , {{ show.time | time:"H:i"}}</p>
                    <p>{{ show.event.location }}</p>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-6 showDates">
                    <p> Dates :</p>
                    {% for dates in dates %}
                    <a href="{% url 'events:show' dates.id %}">
                        <span class="{% if dates.date == show.date %}
                                showButton__active {% else %} showButton {% endif%}
                        ">{{ dates.date | date:"d M"  }} , {{dates.time | time:"H:i"}}</span>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </header>
    <div class="wrapper">
        <div class="main">
            <div id="seats-container">
                <svg id="seats">
                </svg>
            </div>
        </div>
        <div class="sidebar">
            <div id="alerts">
                <div class='alert alert-blue text-center alert-sm small m-0'>
                    No Seats Selected Yet.
                </div>
            </div>
            <div class="Purchase">
                <table id="tickets" class="table">
                </table>
            </div>
            <hr>
            <div id="totalAmount">
            </div>
            <div class="purchaseButton">
                <form id="newPurchaseForm" method="POST">
                    {% csrf_token %}
                    <input name="seatId" type="hidden" id="seatId" value="" />
                    <input name="seatName" type="hidden" id="seatName" value="" />
                    <input name="ticketTotal" type="hidden" id="ticketTotal" value="" />
                    <button id="btnPurchase" class="btn btn-success btn-block" disabled>Checkout</button>
                </form>
            </div>
        </div>
    </div>
</section>
<style>
    body {
        overflow: hidden;
    }
</style>
<script src="{% static 'js/d3.min.js' %}"></script>
<script src="{% static 'js/seat.js' %}"></script>
{% endblock %}

pages/templates/events/show_old.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
{% load humanize %}
{% include 'partials/_alerts.html' %}
{% include 'partials/_navbar.html' %}
<section class="show">
    <form>
        <input name="apiLink" type="hidden" id="apiLink" value="http://127.0.0.1:8000/api/?show={{show.id}}" />
    </form>
    <header class="showHeader">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2 col-md-2 col-lg-2">
                    <img src={{show.event.cover_image.url}} class="showImg" alt={{show.event}}>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3 showDetails">
                    <h6>{{ show.event }}</h6>
                    <p>{{ show.date | date:"d M Y" }} , {{ show.time | time:"H:i"}}</p>
                    <p>{{ show.event.location }}</p>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-3 showDates">
                    <p> Dates :</p>
                    {% for dates in dates %}
                    <a href="{% url 'events:show' dates.id %}">
                        <span class="{% if dates.date == show.date %}
                                showButton__active {% else %} showButton {% endif%}
                            ">{{ dates.date | date:"d M"  }} , {{dates.time | time:"H:i"}}</span>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </header>
    <div class="wrapper">
        <div class="main">
            <div id="newPurchaseForm">
                <form>
                    <div class="tickets">
                        <div class="newShowDetails">
                            <h4>Theatre Name</h4>
                            <small class="text-light">Fri 13, 2019 - 7.30PM<br> Kuwait</small>
                        </div>
                        <div id="ticketView">
                            <div id="alerts">
                                <div class='alert alert-warning text-center alert-sm m-0'>
                                    No Seats Selected Yet.
                                </div>
                            </div>
                            <table id="tickets" class="table  table-striped">
                            </table>
                        </div>
                        <div class="purchaseBtn">
                            <div id="totalAmount"></div>
                            <button id="btnPurchase" class="btn btn-primary btn-block" disabled>Purchase</button>
                        </div>
                    </div>
                </form>
            </div>
            <div id="seats-container">
                <svg id="seats">
                </svg>
            </div>
        </div>
        <!-- <div class="sidebar">
            <div id="alerts">
                <div class='alert alert-warning text-center alert-sm small m-0'>
                    No Seats Selected Yet.
                </div>
            </div>
            <div class="Purchase">
                <table id="tickets" class="table">
                </table>
            </div>
            <hr>s
            <div id="totalAmount">
            </div>
            <div class="purchaseButton">
                <form id="newPurchaseForm" method="POST">
                    {% csrf_token %}
                    <input name="seatId" type="hidden" id="seatId" value="" />
                    <input name="seatName" type="hidden" id="seatName" value="" />
                    <input name="ticketTotal" type="hidden" id="ticketTotal" value="" />
                    <button id="btnPurchase" class="btn btn-primary btn-block">Checkout</button>
                </form>
            </div>
        </div> -->
    </div>
</section>
<style>
    body {
        overflow: hidden;
    }
</style>
<script src="{% static 'js/d3.min.js' %}"></script>
<script src="{% static 'js/seat.js' %}"></script>
{% endblock %}