api/urls.py
from django.urls import path,include
from .views import SeatListView, SeatDetailView

urlpatterns = [
    path('', SeatListView.as_view()),
    path('<int:pk>', SeatDetailView.as_view())
]

events/urls.py
from django.urls import path,include
from . import views
    
app_name = 'events'

urlpatterns = [
    path('',views.events, name="events"),
    path('<int:show_id>/checkout',views.checkout, name="checkout"),
    path('<int:show_id>/booking_confirmation',views.booking_confirmation, name="booking_confirmation"),
    path('<int:show_id>',views.show, name="show"),
    path('<slug>',views.event, name="event"),
]

planetx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/templates/partials/_alerts.html
{% if messages %}
{% for message in messages %}

<div id="message" class="container">
    <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <!-- <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button> -->
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <!-- <i class="fas fa-exclamation-circle"></i> Error : -->
            {% else %}
            <!-- <i class="far fa-check-circle mr-2"></i>{{ message.tags|title }} -->
            {% endif %}
        </strong>
        {{ message }}
    </div>
</div>

{% endfor %}
{% endif %}

pages/templates/partials/_datatables.html
{% load static %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
<script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

<script>
    $(document).ready(function () {
        $('#attendeesTable').DataTable();
    });
</script>

pages/templates/partials/_footer.html
{% load static %}
<footer>
    <div class="container">
        <hr>
        <div class="row footerLinks">
            <div class="col-md-4">
                <h6>Helpful Links</h6>
                <p>My Account</p>
                <p>Events</p>
                <p>Trending Now</p>
                <p>Coming Soon</p>
                <p>New Arrivals</p>
            </div>
            <div class="col-md-4">
                <h6>Company</h6>
                <p>Who We Are</p>
                <p>Our Blog</p>
                <p>Theatres</p>
                <p>Contact Us</p>
                <p>Work With Us</p>
            </div>
            <div class="col-md-4">
                <h6>Legal</h6>
                <p>Terms & Conditions</p>
                <p>Privacy Policy</p>
                <p>Ad and Cookie Policy</p>
                <p>Testimonial Disclaimer</p>
                <p>Social Responsibility</p>
            </div>
        </div>
        <hr class="my-5 bg-light">
        <div class="row social-links justify-content-between">
            <div class="col-md-6">
                <h6>PlanetX</h6>
            </div>
            <div class="col-md-6">
                <div class="small">&copy; Planetx 2020</div>
            </div
        </div>
    </div>
</footer>

pages/templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-md">
    <div class="container">
        <a class="navbar-brand" href="/">PlanetX</a>
        <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse"
            data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false"
            aria-labinrel="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'events:events' %}">Events</a>
                </li>
                                                                           <li class="nav-item">
                    <a class="nav-link" href="#">About</a>                                                                      
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
    
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.first_name }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'profile'%}"><i class="fas fa-user"></i> Profile</a>
                        <a class="dropdown-item"
                            href="javascript:{document.getElementById('logout').submit()}"><i class="fas fa-sign-in-alt"></i> Logout</a>
                        <form action="{% url 'logout' %}" method="POST" id="logout">
                            {% csrf_token %}
                            <input  type="hidden">
                        </form>
                    </div>
                </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'register'%}" class="nav-link auth">
                            Register
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'login'%}" class="nav-link">
                            Login
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>